From ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y -q python-opencv \
                       python-pip \
                       libopencv-dev \
                       libcanberra-gtk3-module \
                       vim-tiny \
                       mosquitto-clients

RUN pip install paho-mqtt

RUN mkdir save
COPY . /save
WORKDIR /save

ENTRYPOINT ["python" ]
CMD ["save.py" ]